[project]
name = "neuronal-decay"
version = "1.0.0"
description = ""
authors = [{name = "Your Name",email = "you@example.com"}]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "marimo (>=0.13.1,<0.14.0)"
]

[tool.poetry.dependencies]
torch = [
    { markers = "extra == 'cpu' and extra != 'cuda'", source = "pytorch-cpu" },
    { markers = "extra == 'cuda' and extra != 'cpu'", source = "pytorch-cuda" },
]
torchvision = [
    { markers = "extra == 'cpu' and extra != 'cuda'", source = "pytorch-cpu" },
    { markers = "extra == 'cuda' and extra != 'cpu'", source = "pytorch-cuda" },
]

[project.optional-dependencies]
cpu = ["torch (==2.7.0)", "torchvision"]
cuda = ["torch (==2.7.0)", "torchvision"]

[[tool.poetry.source]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
priority = "explicit"

[[tool.poetry.source]]
name = "pytorch-cuda"
url = "https://download.pytorch.org/whl/cu126"
priority = "explicit"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
package-mode = false
